spring.application.name=sistema-api

# Configuração do H2
spring.datasource.url=jdbc:h2:mem:sistema_alan api
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

asaas.token=${ASAAS_TOKEN:${ASAAS_TOKEN_ENV:}}
resend.token=${RESEND_TOKEN:${RESEND_TOKEN_ENV:}}

# Se o Render fornecer a variável MONGODB_URI, ele usa a nuvem. 
# Se não (no seu PC), ele usa o localhost.
spring.mongodb.uri=mongodb+srv://AlanSystem:1234@cluster0.owyxobz.mongodb.net/AlanSystemDB?retryWrites=true&w=majority
mongodb+srv://AlanSystem:1234@cluster0.owyxobz.mongodb.net/AlanSystemDB?retryWrites=true&w=majority
