spring.application.name=sistema-api

# # Configuração do H2
# spring.datasource.url=jdbc:h2:mem:sistema_alanapi
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.jpa.hibernate.ddl-auto=update

# Conexão com o Mongo
spring.mongodb.uri=${MONGO_URI}
spring.data.mongodb.auto-index-creation=true

# Configurações customizadas que você vai usar no Service
# O @Value("${asaas.token}") vai ler o que estiver no .env
asaas.token=${ASAAS_API_TOKEN}
zapsign.token=${ZAPSIGN_API_TOKEN}
resend.token=${RESEND_API_TOKEN}